# Generated by Django 4.1 on 2022-08-18 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MendeleyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mendeley_username', models.CharField(max_length=250)),
                ('mendeley_password', models.CharField(max_length=250)),
                ('mendeley_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(default='www.mendeley.com', max_length=250)),
                ('access_level', models.CharField(choices=[('private', 'private'), ('invite_only', 'invite_only'), ('public', 'public')], default='private', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mendeley_id', models.CharField(max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('tags', models.CharField(max_length=512)),
                ('websites', models.CharField(default='', max_length=1024)),
                ('abstract', models.TextField(null=True)),
                ('year', models.DateTimeField(default=datetime.datetime(2022, 8, 18, 17, 4, 41, 16715, tzinfo=datetime.timezone.utc))),
                ('keywords', models.CharField(blank=True, max_length=250)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('classified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(to='melastic.mendeleygroup')),
            ],
        ),
    ]
